'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
s = 0
def fib(n):
    if n == 0 or n == 1: return 1
    else:
        return fib(n-1) + fib(n-2)
Ns = []
n = 2
while fib(n) < 4e6:
    Ns.append(fib(n))
    n += 1


for num in Ns:
    if num%2 == 0: s += num

print s




